#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
GHIAS Assistant
Automatic Daily Report Generator
"""

from datetime import datetime
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]

REPORT_FOLDER = PROJECT_ROOT / "docs" / "DAILY_REPORTS" / "AUTO"


def create_report(work_description):

    REPORT_FOLDER.mkdir(
        parents=True,
        exist_ok=True
    )

    today = datetime.now().strftime("%Y-%m-%d")

    report_file = REPORT_FOLDER / f"{today}.md"

    content = f"""
# GHIAS Daily Report

## Date
{today}

## Project
GHIAS

## Work Description

{work_description}

## Generated By

GHIAS Assistant

"""

    report_file.write_text(
        content,
        encoding="utf-8"
    )

    return report_file



if __name__ == "__main__":

    text = input(
        "What did you do today?\n> "
    )

    file = create_report(text)

    print()
    print("Report created:")
    print(file)