#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
GHIAS Assistant
Professional Daily Report Generator v0.7
"""

from datetime import datetime
from pathlib import Path



PROJECT_ROOT = Path(__file__).resolve().parents[2]



def get_report_folder():

    now = datetime.now()

    folder = (
        PROJECT_ROOT
        / "docs"
        / "DAILY_REPORTS"
        / "AUTO"
        / str(now.year)
        / f"{now.month:02d}"
    )

    folder.mkdir(
        parents=True,
        exist_ok=True
    )

    return folder




def create_report(work_description, project_info, changes):

    now = datetime.now()


    report_folder = get_report_folder()


    report_file = (
        report_folder /
        f"{now.strftime('%Y-%m-%d')}.md"
    )


    changed_text = ""


    all_changes = (
        changes["modified"]
        +
        changes["added"]
        +
        changes["deleted"]
    )


    if all_changes:

        for item in all_changes:

            changed_text += f"- {item}\n"


    else:

        changed_text = "No changes"



    content = f"""
# GHIAS Daily Report


## Date

{now.strftime('%Y-%m-%d')}


## Time

{now.strftime('%H:%M:%S')}


## Project

{project_info["project"]}


## Path

{project_info["path"]}


## Branch

{project_info["branch"]}


## Last Commit

{project_info["last_commit"]}



## Changed Files

{changed_text}



## Work Description

{work_description}



## Generated By

GHIAS Assistant v0.7

"""


    report_file.write_text(
        content,
        encoding="utf-8"
    )


    return report_file