#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
GHIAS Assistant
Professional Daily Report Generator
"""

from datetime import datetime
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]


def get_report_folder():

    now = datetime.now()

    folder = (
        PROJECT_ROOT
        / "docs"
        / "DAILY_REPORTS"
        / "AUTO"
        / str(now.year)
        / f"{now.month:02d}"
    )

    folder.mkdir(
        parents=True,
        exist_ok=True
    )

    return folder



def create_report(work_description):

    now = datetime.now()

    report_folder = get_report_folder()

    file_name = (
        f"{now.strftime('%Y-%m-%d')}.md"
    )

    report_file = report_folder / file_name


    content = f"""
# GHIAS Daily Report


## Date

{now.strftime('%Y-%m-%d')}


## Time

{now.strftime('%H:%M:%S')}


## Project

GHIAS


## Work Description

{work_description}


## Generated By

GHIAS Assistant

"""


    report_file.write_text(
        content,
        encoding="utf-8"
    )


    return report_file



if __name__ == "__main__":

    print(
        "GHIAS Daily Report Generator"
    )

    work = input(
        "\nWhat did you do today?\n> "
    )


    report = create_report(work)


    print(
        "\nReport created:"
    )

    print(report)